#!/usr/bin/env bash
#
# og - Organize files into tag-specific sub-directories

# Directory containing markdown files
SOURCE_DIR="$ZK_REVIEWED_DIR"  # see `stow/zsh/.zshenv`
DEST_DIR="$ZK_STORE_DIR" # see `stow/zsh/.zshenv`


# Iterate through all markdown files in the source directory
find "$SOURCE_DIR" -type f -name "*.qmd" | while read -r file; do
  echo "Processing $file"

  # Extract the tag from the file. This assumes the tag is on the line
  # immediately following "tags:"
  tag=$(awk '/tags:/{getline; print; exit}' "$file" | sed -e 's/^ *- *//' -e 's/^ *//;s/ *$//')

  echo "Found tag $tag"

  # If a tag is found, proceed with moving the file
  if [ ! -z "$tag" ]; then
    # Create the target directory if it doesn't exist
    TARGET_DIR="$DEST_DIR/$tag"
    mkdir -p "$TARGET_DIR"

    # Move the file to the target directory
    mv "$file" "$TARGET_DIR/"
    echo "Moved $file to $TARGET_DIR"
  else
    echo "No tag found for $file"
  fi

done

echo "Done 🪷"
