[env]
    TERM = "xterm-256color"

[window]
    padding.x = 10
    padding.y = 10
    decorations = "Buttonless" # remove macOS buttons
    opacity = 0.8
    blur = true

[font]
    size = 16
    normal.family = "MesloLGS Nerd Font Mono"