
# Catppuccin status-bar settings
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W"         # Inactive window text
set -g @catppuccin_window_current_text " #W" # Active window text
set -g status-left "#{E:@catppuccin_status_session}#[bg=default,fg=#{@thm_surface_0}]"
set -g status-right "#{E:@catppuccin_status_uptime}#[bg=default,fg=#{@thm_surface_0}]"

# https://github.com/catppuccin/tmux/issues/409#issuecomment-3463618644
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_left_separator "#[bg=default,fg=#{@thm_overlay_2}]#[bg=#{@thm_overlay_2},fg=#{@thm_surface_0}]"
set -g @catppuccin_window_right_separator "#[bg=default,fg=#{@thm_surface_0}]"
set -g @catppuccin_window_current_left_separator "#[bg=default,fg=#{@thm_mauve}]#[bg=#{@thm_mauve},fg=#{@thm_bg}]"
set -g @catppuccin_window_current_middle_separator "#[fg=#{@thm_mauve}]█"
set -g @catppuccin_window_current_right_separator "#[bg=default,fg=#{@thm_surface_1}]"
set -g @catppuccin_status_background "none"

# https://github.com/catppuccin/tmux/issues/68
set -g @catppuccin_window_middle_separator " "

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
