# Configure TPM to use XDG-compliant path
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins/"

# To install plugins:
# >> git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
# >> "<leader> I" inside "tmux" to install
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "catppuccin/tmux#v2.1.3"
set -g @plugin "alexforsythe/tmux-which-key"
set -g @plugin "tmux-plugins/tmux-sensible" # better defaults
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"

# -- tmux-dotbar -------------------------------------------------------------
set -g @plugin "vaaleyard/tmux-dotbar"
set -g @tmux-dotbar-position top
set -g @tmux-dotbar-show-maximized-icon-for-all-tabs true
set -g @tmux-dotbar-bold-status true
set -g @tmux-dotbar-bold-current-window true
set -g @tmux-dotbar-bg "default"
set -g @tmux-dotbar-fg "#585b70"
set -g @tmux-dotbar-fg-current "#cdd6f4"
set -g @tmux-dotbar-fg-session "#9399b2"
set -g @tmux-dotbar-fg-prefix "#cba6f7"
