-- [[ Avante : AI-powered code completion and chat in Neovim ]]
-- Provides Cursor-like AI assistance with inline code generation
-- Authentication: Set ANTHROPIC_API_KEY environment variable
-- See https://github.com/yetone/avante.nvim

-- IGNORE: package uses ANTHROPIC API key, not Claude Code

return {
  -- "yetone/avante.nvim",
  -- -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  -- -- ⚠️ must add this setting! ! !
  -- build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
  --   or "make",
  -- event = "VeryLazy",
  -- version = false, -- Never set this value to "*"! Never!
  -- ---@module 'avante'
  -- ---@type avante.Config
  -- opts = {
  --   -- add any opts here
  --   -- this file can contain specific instructions for your project
  --   instructions_file = "avante.md",
  --   -- for example
  --   provider = "claude",
  --   providers = {
  --     claude = {
  --       endpoint = "https://api.anthropic.com",
  --       model = "claude-sonnet-4-5-20250929",
  --       timeout = 30000, -- Timeout in milliseconds
  --       extra_request_body = {
  --         temperature = 0.3, -- Lower temperature for more deterministic code generation
  --         max_tokens = 8192, -- Maximum output tokens for Claude models
  --       },
  --     },
  --   },
  -- },
  -- dependencies = {
  --   "nvim-lua/plenary.nvim", -- Lua utility functions
  --   "MunifTanjim/nui.nvim", -- UI component library
  --   "nvim-telescope/telescope.nvim", -- File picker for file selection
  --   "stevearc/dressing.nvim", -- Enhanced UI for inputs and selections
  --   "echasnovski/mini.nvim", -- Icons and additional utilities
  --   {
  --     -- Image pasting support for AI chat (paste images directly into prompts)
  --     "HakonHarnes/img-clip.nvim",
  --     event = "VeryLazy",
  --     opts = {
  --       -- recommended settings
  --       default = {
  --         embed_image_as_base64 = false,
  --         prompt_for_file_name = false,
  --         drag_and_drop = {
  --           insert_mode = true,
  --         },
  --         -- required for Windows users
  --         use_absolute_path = true,
  --       },
  --     },
  --   },
  --   {
  --     -- Markdown rendering in Avante chat windows for better readability
  --     "MeanderingProgrammer/render-markdown.nvim",
  --     opts = {
  --       file_types = { "markdown", "Avante" },
  --     },
  --     ft = { "markdown", "Avante" },
  --   },
  -- },
}
