# Configure TPM to use XDG-compliant path
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins/"

# To install plugins:
# >> git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
# >> "<leader> I" inside "tmux" to install
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "catppuccin/tmux#v2.1.3"
set -g @plugin "alexforsythe/tmux-which-key"
set -g @plugin "tmux-plugins/tmux-sensible" # better defaults
set -g @plugin "joshmedeski/tmux-nerd-font-window-name"
set -g @plugin "vaaleyard/tmux-dotbar"

# Quality of life improvements
set -g escape-time 0 # prevent delay due to <ESC>
set -g mouse on # enable use of mouse
set -g repeat-time 1000 # repeat key without need for <leader>
set -g history-limit 50000  # n lines stored
set -g default-terminal "${TERM}" # true colors
set -g terminal-overrides ",xterm-256color:RGB" # true colors
set -g allow-passthrough on # required by image.nvim to display images
set -g base-index 1 # window index start at 1
set -g pane-base-index 1 # pane index start at 1
set -g renumber-windows on # renumber if middle pane/window closed

# Configure automatic window renaming
set -g status-interval 10 # every _ seconds
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}"

# Configure status-bar
set -g status on
set -g status-position top
set -g status-justify centre
set -g status-left-length 100
set -g status-right-length 100

set -g @tmux-dotbar-position top
set -g @tmux-dotbar-show-maximized-icon-for-all-tabs true
set -g @tmux-dotbar-bold-status true
set -g @tmux-dotbar-bold-current-window true
set -g @tmux-dotbar-bg "default"
set -g @tmux-dotbar-fg "#585b70"
set -g @tmux-dotbar-fg-current "#cdd6f4"
set -g @tmux-dotbar-fg-session "#9399b2"
set -g @tmux-dotbar-fg-prefix "#cba6f7"

source ~/.config/tmux/remappings.conf

# MUST BE LAST LINE - TPM will load plugins including catppuccin
run "~/.config/tmux/plugins/tpm/tpm"
