# -- options ------------------------------------------------------------------
source-file ~/.config/tmux/conf.d/options.conf

# -- bindings ----------------------------------------------------------------
source-file ~/.config/tmux/conf.d/bindings.conf

# -- plugins -----------------------------------------------------------------
source-file ~/.config/tmux/conf.d/plugins.conf

# MUST BE LAST LINE - TPM will load plugins
run "~/.config/tmux/plugins/tpm/tpm"
